name: Update Flake

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: echo 'No way' && exit 1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.nix
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get latest release version
          release=$(curl -sL "https://api.github.com/repos/labi-le/deal/releases/latest" | jq -r '.tag_name')
          version=${release#v}
          echo "VERSION=$version" >> $GITHUB_ENV
          
          curl -sL "https://github.com/labi-le/deal/releases/download/$release/sha256.sum" -o sha256.sum
          
          amd64_hash=$(grep "*deal-x86_64-unknown-linux-gnu.tar.xz" sha256.sum | cut -d ' ' -f1)
          arm_hash=$(grep "*deal-aarch64-unknown-linux-gnu.tar.xz" sha256.sum | cut -d ' ' -f1)
          
          amd64_sri=$(nix hash convert --to sri "sha256:$amd64_hash")
          arm_sri=$(nix hash convert --to sri "sha256:$arm_hash")
          
          echo "AMD64_SRI=$amd64_sri" >> $GITHUB_ENV
          echo "ARMV6_SRI=$arm_sri" >> $GITHUB_ENV
          
          # Update version
          sed -i "s/version = \"[^\"]*\"/version = \"$version\"/" flake.nix
          # Update AMD64 hash
          sed -i "s|hash = \"sha256-[^\"]*\"; # x86_64-linux|hash = \"$amd64_sri\"; # x86_64-linux|" flake.nix
          # Update ARM hash
          sed -i "s|hash = \"sha256-[^\"]*\"; # aarch64-linux|hash = \"$arm_sri\"; # aarch64-linux|" flake.nix
          
          # Update flake.lock
          nix flake update
          
          rm sha256.sum

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          commit-message: "chore: update flake.nix and flake.lock to v${{ env.VERSION }}"
          title: "Update flake.nix to v${{ env.VERSION }}"
          body: |
            Automatic update of flake.nix for release v${{ env.VERSION }}
            
            Updates:
            - Version: ${{ env.VERSION }}
            - x86_64-linux hash: ${{ env.AMD64_SRI }}
            - aarch64-linux hash: ${{ env.ARMV6_SRI }}
            - Updated flake.lock
          branch: update-flake
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge